### ISSUE TITLE
Bug with folder name.

### ISSUE THREAD

**Issue by JZ6** [Cooleyy/EasySpawner#1]
Can not use mod unless the mod is placed in a folder named EasySpawner, but mod managers set the folder name to Cooleyy-EasySpawner-1.0.1

**Comment by Cooleyy** [comment]
Oh thanks for letting me know, I've disabled downloading from mod managers for now. Might fix this in the future

**Comment by mattyteds** [comment]
Still available on r2modman/Thunderstore. Did you fix this or have not disabled it?

**Comment by Cooleyy** [comment]
Should have clarified I meant disabled mod managers on Nexusmods not thunderstore, dont think I can change it on thunderstore

**Comment by Cooleyy** [comment]
Pushed a fix for this, file name can now be anything. Mod managers should work now

**Comment by JZ6** [comment]
blazing fast work, thanks friend!
