### ISSUE TITLE
Incompatible with Hearth and Home

### ISSUE THREAD

**Issue by nilsroesel** [Cooleyy/EasySpawner#17]

**Comment by MSchmoecker** [comment]
Please provide a log where the error is shown

**Comment by nilsroesel** [comment]
There is no error in the console shown. Its just not loading the mod at all

**Comment by Cooleyy** [comment]
Have you got the most recent version?

**Comment by nilsroesel** [comment]
1st of September Release

**Comment by nilsroesel** [comment]
I update bepinex now it worked
