### ISSUE TITLE
Missplaced Window

### ISSUE THREAD

**Issue by nilsroesel** [Cooleyy/EasySpawner#18]
![Valheim Screenshot 2021 10 05 - 16 07 47 79](https://user-images.githubusercontent.com/24684707/136039849-613354a3-dc4f-4410-a403-dc08fa9c647d.png)
Screen Resolution: 2560x1440
Its also cut off on other resolutions

**Comment by Cooleyy** [comment]
open inventory and use your mouse to move the window
