### ISSUE TITLE
AssetBundle error

### ISSUE THREAD

**Issue by Alreadyded** [Cooleyy/EasySpawner#2]
The asset bundle fails to load. Rendering the mod unusable.
![Capture](https://user-images.githubusercontent.com/80360167/110534683-fb2f1e00-80e4-11eb-8b6f-925ee6d9848a.PNG)

**Comment by Cooleyy** [comment]
Cant know exactly whats going on but its probably due to you downloading through the risk of rain modloader. I disabled downloads through mod loaders on Nexusmods but cant do that for thunderstore unfortunately
