### ISSUE TITLE
Getting Unity error

### ISSUE THREAD

**Issue by Aurodis** [Cooleyy/EasySpawner#20]
![ad153fde01f0bc2ab7c35c89a9ed7844](https://user-images.githubusercontent.com/95053855/143500897-0abfa59d-7649-414a-9794-f1ce411fc4e0.png)

I have tried redoing the unity dll files but continue to get this error. Not sure what i need to do to fix?

**Comment by Cooleyy** [comment]
Rebuilding mod seems to have fixed it on my end, update broke it. Please redownload and let me know if its fixed.

**Comment by Aurodis** [comment]
It is fixed.

**Comment by Cooleyy** [comment]
![okayge](https://cdn.betterttv.net/emote/619ff372b50549e7e500e709/3x)
